name: Publish to npm

on:
  push:
    branches:
      - main

  # Triggers after the CI workflow completes on the main branch
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  publish:
    # Ensure the workflow only runs if the push was to main and CI succeeded.
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow == 'CI Pipeline' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
